package oopsbannerapp;


/**
 * PrintOOPS class
 *
 * <p>This class demonstrates <b>UC2: Render OOPS as Banner using Print Statements</b>.
 * It prints the word {@code "OOPS"} in a banner format using spaces and
 * asterisk ({@code *}) characters.</p>
 *
 * <p>The banner is generated by printing each line individually using
 * {@code System.out.println()} combined with {@code String.join()}.
 * Each line is constructed by joining multiple strings that represent
 * individual characters (O, O, P, S).</p>
 *
 * <p>This program helps in understanding:</p>
 * <ul>
 *   <li>ASCII art creation using characters</li>
 *   <li>String concatenation and joining</li>
 *   <li>Multiple print statements for multi-line output</li>
 *   <li>Basic Java program structure</li>
 * </ul>
 *
 * @author Prabhu
 * @version 3.0
 */

public class PrintOOPS
{
    /**
     * Main method – Entry point of the Java application.
     *
     * <p>When the program is executed, this method prints seven lines
     * of output that together form the banner representation of the
     * word {@code "OOPS"}.</p>
     *
     * <p>Each line is created by joining fixed-width strings to ensure
     * proper alignment of the banner.</p>
     *
     * @param args command-line arguments (not used)
     */

    public static void main(String[] args)
    {
        System.out.println(String.join("",
                "  *****  ",
                "  *****  ",
                " ******  ",
                "  *****  "
        ));

        System.out.println(String.join("",
                " *     * ",
                " *     * ",
                " *     * ",
                " *        "
        ));

        System.out.println(String.join("",
                " *     * ",
                " *     * ",
                " *     * ",
                " *        "
        ));

        System.out.println(String.join("",
                " *     * ",
                " *     * ",
                " ******  ",
                "  *****  "
        ));

        System.out.println(String.join("",
                " *     * ",
                " *     * ",
                " *        ",
                "       * "
        ));

        System.out.println(String.join("",
                " *     * ",
                " *     * ",
                " *        ",
                "       * "
        ));

        System.out.println(String.join("",
                "  *****  ",
                "  *****  ",
                " *        ",
                "  *****  "
        ));
    }

}
